### ISSUE TITLE
MAUI app after wrapping on android platform 

### ISSUE THREAD

**Issue by ShaikhAtikAhmed** [microsoftconnect/intune-app-wrapping-tool-android#101]
**Questions to Ask Before Submission**
1. Does you app launch successfully without wrapping? Yes
2. Have you reviewed the [prerequisites](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#fulfill-the-prerequisites-for-using-the-app-wrapping-tool) for App Wrapping? Yes
3. Does your issue have a solution in the [Troubleshooting Guide?](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/wiki/Troubleshooting-the-App-Wrapper) No
4. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for similar issues?No
5. Are you using the latest version of the App Wrapper?Yes

**Describe the bug:**
 Hi Team, we have developed a MAUI android which is working fine on devices.

As per our business need we are wrapping the application with Intune Wrapping app, Wrapping of the app is getting sucess.

Post wrapping the app it is getting crashed on launch. 

when we have gone through the debug report it status it is giving
" ANDROID.RUNTIME.JAVAPROXYTHROWABLE: [SYSTEM.NULLREFERENCEEXCEPTION]: OBJECT REFERENCE NOT SET TO AN INSTANCE OF AN OBJECT."

OS: Windows 11
Visual Studio 2022 : 17.9.6
Android version 14 

**To Reproduce**

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is crashing post-wrapping, do you have app logs for the crash itself? 
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors? 

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 6]
 - OS Version: [e.g. Android 13]

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For pre-wrapping errors, does the app build without being wrapped?
- For post-wrapping errors, does the app launch without being wrapped?
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by kanishkaBagga** [comment]
@ShaikhAtikAhmed - The App Wrapping Tool does not support MAUI apps. You should leverage the MAUI SDK directly instead. https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android

**Comment by ShaikhAtikAhmed** [comment]
Hi Kanishka, can you help me out with code sample to integrate the same.

**Comment by kanishkaBagga** [comment]
@ShaikhAtikAhmed , please let us know if this resolves your concern, and we can close the issue

**Comment by kanishkaBagga** [comment]
Closing this issue since no further questions
