### ISSUE TITLE
IntuneMAMPackager.jar not exist

### ISSUE THREAD

**Issue by ayaaboud** [microsoftconnect/intune-app-wrapping-tool-android#102]
When installing the tool IntuneMAMPackager.jar not created in jars.

**Comment by kanishkaBagga** [comment]
@ayaaboud  looking into this

**Comment by kanishkaBagga** [comment]
@ayaaboud - can you please share more details - 
1. Does you app launch successfully without wrapping? 
2. Have you reviewed the [prerequisites](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#fulfill-the-prerequisites-for-using-the-app-wrapping-tool) for App Wrapping? 
3. Does your issue have a solution in the [Troubleshooting Guide?](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/wiki/Troubleshooting-the-App-Wrapper) 
4. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for similar issues? 
5. Are you using the latest version of the App Wrapper? 

Describe the bug:

To Reproduce
Steps to reproduce the behavior:

**Comment by meghandaly** [comment]
This issue does not include enough actionable detail and is being closed.
