### ISSUE TITLE
I am not able to wrap my app

### ISSUE THREAD

**Issue by rohanthakran** [microsoftconnect/intune-app-wrapping-tool-android#104]
PS C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool> Invoke-AppWrappingTool -InputPath "C:\Users\Admin\Downloads\app-release.apk" -OutputPath "C:\Users\Admin\Desktop\starbuckswrapper.apk"
Application wrapping in progress. App Wrapping Tool Version: 1.0.4214.3
C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\sourceApk\res\layout\number_picker_material.xml:2: error: resource android:style/TextAppearance.MisspelledSuggestion is private.
error: failed linking file resources.
Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:157)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:104)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:205)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:85)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:238)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:60)
        brut.androlib.exceptions.AndrolibException: brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_82035255766092429456168612730659179859.tmp, link, -o, C:\Users\Admin\AppData\Local\Temp\APKTOOL2576978771637335834.tmp, --package-id, 127, --min-sdk-version, 23, --target-sdk-version, 33, --version-code, 4, --version-name, 1.3, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL8484535421596641615.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\framework\1.apk, --manifest, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\sourceApk\AndroidManifest.xml, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\sourceApk\build\resources.zip]
                brut.androlib.ApkBuilder.buildResourcesFull(ApkBuilder.java:320)
                brut.androlib.ApkBuilder.buildResources(ApkBuilder.java:217)
                brut.androlib.ApkBuilder.build(ApkBuilder.java:102)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:143)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:104)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:205)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:85)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:238)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:60)
        brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_82035255766092429456168612730659179859.tmp, link, -o, C:\Users\Admin\AppData\Local\Temp\APKTOOL2576978771637335834.tmp, --package-id, 127, --min-sdk-version, 23, --target-sdk-version, 33, --version-code, 4, --version-name, 1.3, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL8484535421596641615.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\framework\1.apk, --manifest, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\sourceApk\AndroidManifest.xml, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\sourceApk\build\resources.zip]
                brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:241)
                brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:376)
                brut.androlib.ApkBuilder.buildResourcesFull(ApkBuilder.java:295)
                brut.androlib.ApkBuilder.buildResources(ApkBuilder.java:217)
                brut.androlib.ApkBuilder.build(ApkBuilder.java:102)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:143)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:104)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:205)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:85)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:238)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:60)
        brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_82035255766092429456168612730659179859.tmp, link, -o, C:\Users\Admin\AppData\Local\Temp\APKTOOL2576978771637335834.tmp, --package-id, 127, --min-sdk-version, 23, --target-sdk-version, 33, --version-code, 4, --version-name, 1.3, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL8484535421596641615.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\framework\1.apk, --manifest, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\sourceApk\AndroidManifest.xml, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-6658850097313221387\sourceApk\build\resources.zip]
                brut.util.OS.exec(OS.java:104)
                brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:237)
                brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:376)
                brut.androlib.ApkBuilder.buildResourcesFull(ApkBuilder.java:295)
                brut.androlib.ApkBuilder.buildResources(ApkBuilder.java:217)
                brut.androlib.ApkBuilder.build(ApkBuilder.java:102)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:143)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:104)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:205)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:85)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:238)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:60)
Failed to load app resource table.
Verbose logs can be found at: C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingToolLog_20241023_172541.txt.
The application could not be wrapped.

**Comment by rygo-msft** [comment]
Please refile this using one the issue templates and provide all requested information. Our support team is not able to provide support without the information requested in those templates
