### ISSUE TITLE
The application could not be wrapped.

### ISSUE THREAD

**Issue by rohanthakran** [microsoftconnect/intune-app-wrapping-tool-android#105]
Error ---- C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\sourceApk\res\layout\number_picker_material.xml:2: error: resource android:style/TextAppearance.Material.NumberPicker is private.   

PS C:\> Invoke-AppWrappingTool -InputPath C:\Users\Admin\Downloads\app-release.apk -OutputPath C:\Users\Admin\Desktop\app_wrap.apk
Application wrapping in progress. App Wrapping Tool Version: 1.0.4214.3
C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\sourceApk\res\layout\number_picker_material.xml:2: error: resource android:style/TextAppearance.Material.NumberPicker is private.
error: failed linking file resources.
Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:157)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:104)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:205)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:85)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:238)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:60)
        brut.androlib.exceptions.AndrolibException: brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_12322066647437156727802264032303315740.tmp, link, -o, C:\Users\Admin\AppData\Local\Temp\APKTOOL7333312862495492160.tmp, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 4, --version-name, 1.3, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL16831783301948704940.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\framework\1.apk, --manifest, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\sourceApk\AndroidManifest.xml, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\sourceApk\build\resources.zip]
                brut.androlib.ApkBuilder.buildResourcesFull(ApkBuilder.java:320)
                brut.androlib.ApkBuilder.buildResources(ApkBuilder.java:217)
                brut.androlib.ApkBuilder.build(ApkBuilder.java:102)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:143)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:104)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:205)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:85)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:238)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:60)
        brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_12322066647437156727802264032303315740.tmp, link, -o, C:\Users\Admin\AppData\Local\Temp\APKTOOL7333312862495492160.tmp, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 4, --version-name, 1.3, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL16831783301948704940.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\framework\1.apk, --manifest, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\sourceApk\AndroidManifest.xml, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\sourceApk\build\resources.zip]
                brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:241)
                brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:376)
                brut.androlib.ApkBuilder.buildResourcesFull(ApkBuilder.java:295)
                brut.androlib.ApkBuilder.buildResources(ApkBuilder.java:217)
                brut.androlib.ApkBuilder.build(ApkBuilder.java:102)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:143)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:104)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:205)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:85)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:238)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:60)
        brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_12322066647437156727802264032303315740.tmp, link, -o, C:\Users\Admin\AppData\Local\Temp\APKTOOL7333312862495492160.tmp, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 4, --version-name, 1.3, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, -e, C:\Users\Admin\AppData\Local\Temp\APKTOOL16831783301948704940.tmp, -0, arsc, -I, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\framework\1.apk, --manifest, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\sourceApk\AndroidManifest.xml, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-10283300471054120106\sourceApk\build\resources.zip]
                brut.util.OS.exec(OS.java:104)
                brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:237)
                brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:376)
                brut.androlib.ApkBuilder.buildResourcesFull(ApkBuilder.java:295)
                brut.androlib.ApkBuilder.buildResources(ApkBuilder.java:217)
                brut.androlib.ApkBuilder.build(ApkBuilder.java:102)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:143)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:104)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:205)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:85)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:238)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:60)
Failed to load app resource table.
Verbose logs can be found at: C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingToolLog_20241024_103608.txt.
The application could not be wrapped.
PS C:\>

**Comment by rygo-msft** [comment]
Please refile this using one the issue templates and provide all requested information. Our support team is not able to provide support without the information requested in those templates
