### ISSUE TITLE
APK Crashing post Intune wrapping

### ISSUE THREAD

**Issue by RamprasathPnr** [microsoftconnect/intune-app-wrapping-tool-android#99]
**Steps to reproduce the behavior:**
Install intune wrapped APK
Click app from app launcher
The application is crashing when launch itself

**Expected behavior:**
The Application should launch without crashing

**Smartphones**

**Device:** 

VIVO T1
Realme C53
One Plus Nord 2
One Plus 10 Pro
One Plus 8T
Mi 11X
Samsung S21
Samsung Galaxy F22
Vivo V21 5G
Realme X7 5G

**OS:** 
[android 14 ,13,12]

**Screenshots and logs:**

![image](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/assets/17904191/d777e6e0-e927-4847-a1db-9804c991326c)

**Intune app wrapping tool** 

Version of the wrapper -(1.0.3935.1- latest one)
Platform (Java - android native)
For post-wrapping errors, Application is wrapped succesfully but app is crashing when launch

**Intune app wrapping tool Steps**

**STEP 1**
------------------------------------------------------------------------->

Open windows powershell

run following-->
Import-Module "C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\IntuneAppWrappingTool.psm1"

**STEP 2**
------------------------------------------------------------------------->

invoke-AppWrappingTool -InputPath D:\App.apk -OutputPath D:\App_wrapped-unsigned.apk -Verbose

**STEP 3**
------------------------------------------------------------------------->

open cmd --->
Go to build-tools path D:\Android\Sdk\build-tools\34.0.0 ,

zipalign -v -p 4 "D:\App_wrapped-unsigned.apk" "D:\App_wrapped-unsigned-aligned.apk"

**STEP 4**
------------------------------------------------------------------------->

apksigner sign --ks "D:\Keystore.jks" --ks-key-alias abc --out "D:\App_wrapped-signed.apk" "D:\App_wrapped-unsigned-aligned.apk"

**Comment by mikektmobile** [comment]
I see that this says pending future release, any idea of that timing?

**Comment by meghandaly** [comment]
Resolved with latest release, [1.0.4549.6](https://github.com/microsoftconnect/intune-app-wrapping-tool-android/releases/tag/1.0.4549.6).
